source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/BPModels/BPSpecs.git'
#source 'https://cdn.cocoapods.org/'

use_frameworks!

platform :ios, '11.0'

target 'BPKit_Example' do
  pod 'BPKit', :path => '../'

  target 'BPKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
