use_frameworks!

platform :ios, '9.0'

target 'BPKit_Example' do
  pod 'BPKit', :path => '../'

  target 'BPKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
